name: API & Database Testing Action
on: [push, pull_request]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install node
        run: brew install node
      - name: Install packages
        run: npm install pg pgtools express password-hash dotenv
      - name: Setup database
        run: node database/setup_db.js
        env:
          PGDATABASE: health_db
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
      - name: Initialize data
        run: node database/create_tables.js
      - name: Start API
        run: node api/index.js
      - name: Run test suite
        run: cd api-test & npm test